spring:
  application:
    name: Hello

server:
  port: 8081

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
